In [534]:
import pandas as pd

In [535]:
df1 = pd.read_csv("rpj_data.csv", encoding='UTF-8')

In [536]:
df1.head()

                                                                                                          ISO;Score;Rank;Political Context;Rank_Pol;Economic Context;Rank_Eco;Legal Context;Rank_Leg;Social Context;Rank_Soc;Safety;Rank_Saf;Situation;Zone;Country_FR;Country_EN;Country_ES;Country_PT;Country_AR;Country_FA;Year (N);Rank N-1;Rank evolution;Score N-1;Score evolution
NOR;91 89;1;94 87;1;89 84;1;89 5;2;90  48;1;94  74;7;Bonne situation;UE Balkans;Norvège;Norway;... 18;-3                                               29.0
DNK;89 6;2;94  11;2;83 07;4;88 82;3;86 9;5;95   09;5;Bonne situation;UE Balkans;Danemark;Denmar... 48;0                                                12.0
SWE;88 32;3;91 03;4;85 5;2;90  16;1;82 78;20;92 12;22;Bonne situation;UE Balkans;Suède;Sweden;S... 15;0                                                17.0
NLD;87 73;4;88 41;7;84 09;3;87 59;4;87 34;4;91  23;28;Bonne situation;UE Balkans;Pays-Bas;Nethe... 73                                                   NaN
FIN;86 55;5;89 05;6;80 9;5;86  16;6;84 52;14;92 13;21;Bonne situation;UE Balkans;Finlande;Finla... 94;-1                                               39.0

In [537]:
df = pd.read_csv("rpj_data.csv", delimiter=';')
df.head()

,ISO,Score,Rank,Political Context,Rank_Pol,Economic Context,Rank_Eco,Legal Context,Rank_Leg,Social Context,...,Country_EN,Country_ES,Country_PT,Country_AR,Country_FA,Year (N),Rank N-1,Rank evolution,Score N-1,Score evolution
0,NOR,"91,89",1,"94,87",1,"89,84",1,"89,5",2,"90,48",...,Norway,Noruega,Noruega,النرويج,نروژ,2024,1,0,"95,18","-3,29"
1,DNK,"89,6",2,"94,11",2,"83,07",4,"88,82",3,"86,9",...,Denmark,Dinamarca,Dinamarca,الدنمارك,دانمارک,2024,3,1,"89,48","0,12"
2,SWE,"88,32",3,"91,03",4,"85,5",2,"90,16",1,"82,78",...,Sweden,Suecia,Suécia,السويد,سوئد,2024,4,1,"88,15","0,17"
3,NLD,"87,73",4,"88,41",7,"84,09",3,"87,59",4,"87,34",...,Netherlands,Países Bajos,Países Baixos,هولندا,هلند,2024,6,2,87,"0,73"
4,FIN,"86,55",5,"89,05",6,"80,9",5,"86,16",6,"84,52",...,Finland,Finlandia,Finlândia,فنلندا,فنلاند,2024,5,0,"87,94","-1,39"

In [538]:
df.dtypes

ISO                  object
Score                object
Rank                  int64
Political Context    object
Rank_Pol              int64
Economic Context     object
Rank_Eco              int64
Legal Context        object
Rank_Leg              int64
Social Context       object
Rank_Soc              int64
Safety               object
Rank_Saf              int64
Situation            object
Zone                 object
Country_FR           object
Country_EN           object
Country_ES           object
Country_PT           object
Country_AR           object
Country_FA           object
Year (N)              int64
Rank N-1              int64
Rank evolution        int64
Score N-1            object
Score evolution      object
dtype: object

In [539]:
df.columns = df.columns.str.replace(' ', '')
df

,ISO,Score,Rank,PoliticalContext,Rank_Pol,EconomicContext,Rank_Eco,LegalContext,Rank_Leg,SocialContext,...,Country_EN,Country_ES,Country_PT,Country_AR,Country_FA,Year(N),RankN-1,Rankevolution,ScoreN-1,Scoreevolution
0,NOR,"91,89",1,"94,87",1,"89,84",1,"89,5",2,"90,48",...,Norway,Noruega,Noruega,النرويج,نروژ,2024,1,0,"95,18","-3,29"
1,DNK,"89,6",2,"94,11",2,"83,07",4,"88,82",3,"86,9",...,Denmark,Dinamarca,Dinamarca,الدنمارك,دانمارک,2024,3,1,"89,48","0,12"
2,SWE,"88,32",3,"91,03",4,"85,5",2,"90,16",1,"82,78",...,Sweden,Suecia,Suécia,السويد,سوئد,2024,4,1,"88,15","0,17"
3,NLD,"87,73",4,"88,41",7,"84,09",3,"87,59",4,"87,34",...,Netherlands,Países Bajos,Países Baixos,هولندا,هلند,2024,6,2,87,"0,73"
4,FIN,"86,55",5,"89,05",6,"80,9",5,"86,16",6,"84,52",...,Finland,Finlandia,Finlândia,فنلندا,فنلاند,2024,5,0,"87,94","-1,39"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,IRN,"21,3",176,"23,19",157,"23,44",172,"20,03",174,"19,84",...,Iran,Irán,Irã,إيران,ایران,2024,177,1,"24,81","-3,51"
176,PRK,"20,66",177,"18,04",169,"20,59",175,"26,82",167,"17,27",...,North Korea,Corea del Norte,Coreia do Norte,كوريا الشمالية,کره شمالی,2024,180,3,"21,72","-1,06"
177,AFG,"19,09",178,"20,07",164,"29,06",164,"16,35",179,"16,07",...,Afghanistan,Afganistán,Afeganistão,أفغانستان,افغانستان,2024,152,-26,"39,75","-20,66"
178,SYR,"17,41",179,"14,35",177,"19,69",177,"23,75",171,"17,72",...,Syria,Siria,Síria,سوريا,سوریه,2024,175,-4,"27,22","-9,81"
179,ERI,"16,64",180,"12,75",180,"18,54",178,"16,92",178,"20,71",...,Eritrea,Eritrea,Eritreia,إريتريا,اریتره,2024,174,-6,"27,86","-11,22"

In [540]:
# List of columns that need to have commas replaced with periods and converted to float
columns_to_fix = ['Score', 'PoliticalContext', 'EconomicContext', 'LegalContext', 'SocialContext', 'Safety', 'ScoreN-1', 'Scoreevolution']  # Replace with your actual column names

# Loop through each column and apply the transformations
for col in columns_to_fix:
    # Apply string replacement (commas to periods) for all values in the column
    df[col] = df[col].apply(lambda x: str(x).replace(',', '.') if isinstance(x, str) else x)
    
    # Convert to float, using `errors='coerce'` to handle invalid entries as NaN
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Check the results
print(df.head())

   ISO  Score  Rank  PoliticalContext  Rank_Pol  EconomicContext  Rank_Eco  \
0  NOR  91.89     1             94.87         1            89.84         1
1  DNK  89.60     2             94.11         2            83.07         4
2  SWE  88.32     3             91.03         4            85.50         2
3  NLD  87.73     4             88.41         7            84.09         3
4  FIN  86.55     5             89.05         6            80.90         5

   LegalContext  Rank_Leg  SocialContext  ...   Country_EN    Country_ES  \
0         89.50         2          90.48  ...       Norway       Noruega
1         88.82         3          86.90  ...      Denmark     Dinamarca
2         90.16         1          82.78  ...       Sweden        Suecia
3         87.59         4          87.34  ...  Netherlands  Países Bajos
4         86.16         6          84.52  ...      Finland     Finlandia

       Country_PT Country_AR Country_FA Year(N) RankN-1 Rankevolution  \
0        Noruega     النرويج       نروژ    2024       1             0
1      Dinamarca    الدنمارك    دانمارک    2024       3             1
2         Suécia      السويد       سوئد    2024       4             1
3  Países Baixos      هولندا       هلند    2024       6             2
4      Finlândia      فنلندا     فنلاند    2024       5             0

  ScoreN-1 Scoreevolution
0    95.18          -3.29
1    89.48           0.12
2    88.15           0.17
3    87.00           0.73
4    87.94          -1.39

[5 rows x 26 columns]

In [541]:
df['ScoreN-1']

0      95.18
1      89.48
2      88.15
3      87.00
4      87.94
       ...
175    24.81
176    21.72
177    39.75
178    27.22
179    27.86
Name: ScoreN-1, Length: 180, dtype: float64

In [542]:
df['Year(N)']

0      2024
1      2024
2      2024
3      2024
4      2024
       ...
175    2024
176    2024
177    2024
178    2024
179    2024
Name: Year(N), Length: 180, dtype: int64

In [543]:
df[df['Year(N)'] != 2024]
#so this is useless.

Empty DataFrame
Columns: [ISO, Score, Rank, PoliticalContext, Rank_Pol, EconomicContext, Rank_Eco, LegalContext, Rank_Leg, SocialContext, Rank_Soc, Safety, Rank_Saf, Situation, Zone, Country_FR, Country_EN, Country_ES, Country_PT, Country_AR, Country_FA, Year(N), RankN-1, Rankevolution, ScoreN-1, Scoreevolution]
Index: []

[0 rows x 26 columns]

In [544]:
df[['ISO','Zone']].groupby('Zone').count()

                ISO
Zone
Afrique          48
Amériques        28
Asie-Pacifique   32
EEAC             13
MENA             19
UE Balkans       40

In [545]:
df[['ISO','Situation']].groupby('Situation').count()
#okay so it'sn not in english and that could've been reeeeal bad for me BUT 
#I think there's only like 10 things I really have to change since most of the data is in numerical???
#I think this is a win for harshitaTown WOOHOO. 
#maybe translating this is actually all I should do today though.

                         ISO
Situation
Bonne situation            8
Situation difficile       49
Situation plutôt bonne    37
Situation problématique   50
Situation très grave      36

In [546]:
df.rename(columns={'ISO': 'countryCode'}, inplace=True)
df['countryCode']

0      NOR
1      DNK
2      SWE
3      NLD
4      FIN
      ...
175    IRN
176    PRK
177    AFG
178    SYR
179    ERI
Name: countryCode, Length: 180, dtype: object

In [547]:
df.dtypes

countryCode          object
Score               float64
Rank                  int64
PoliticalContext    float64
Rank_Pol              int64
EconomicContext     float64
Rank_Eco              int64
LegalContext        float64
Rank_Leg              int64
SocialContext       float64
Rank_Soc              int64
Safety              float64
Rank_Saf              int64
Situation            object
Zone                 object
Country_FR           object
Country_EN           object
Country_ES           object
Country_PT           object
Country_AR           object
Country_FA           object
Year(N)               int64
RankN-1               int64
Rankevolution         int64
ScoreN-1            float64
Scoreevolution      float64
dtype: object

In [548]:
df.rename(columns={
    'Score': 'score',
    'Rank': 'rank',
    'PoliticalContext': 'polCon',
    'Rank_Pol': 'polRank',
    'EconomicContext': 'ecoCon',
    'Rank_Eco': 'ecoRank',
    'LegalContext': 'legCon',
    'Rank_Leg': 'legRank',
    'SocialContext': 'socCon',
    'Rank_Soc': 'socRank',
    'Safety': 'safCon',
    'Rank_Saf': 'safRank',
    'RankN-1': 'rankLastYear',
    'ScoreN-1': 'scoreLastYear',
    'Rankevolution': 'rankEvo',
    'Scoreevolution': 'scoreEvo'
}, inplace=True)

print(df.columns)

Index(['countryCode', 'score', 'rank', 'polCon', 'polRank', 'ecoCon',
       'ecoRank', 'legCon', 'legRank', 'socCon', 'socRank', 'safCon',
       'safRank', 'Situation', 'Zone', 'Country_FR', 'Country_EN',
       'Country_ES', 'Country_PT', 'Country_AR', 'Country_FA', 'Year(N)',
       'rankLastYear', 'rankEvo', 'scoreLastYear', 'scoreEvo'],
      dtype='object')

In [549]:
print(df.head())

  countryCode  score  rank  polCon  polRank  ecoCon  ecoRank  legCon  legRank  \
0         NOR  91.89     1   94.87        1   89.84        1   89.50        2
1         DNK  89.60     2   94.11        2   83.07        4   88.82        3
2         SWE  88.32     3   91.03        4   85.50        2   90.16        1
3         NLD  87.73     4   88.41        7   84.09        3   87.59        4
4         FIN  86.55     5   89.05        6   80.90        5   86.16        6

   socCon  ...   Country_EN    Country_ES      Country_PT Country_AR  \
0   90.48  ...       Norway       Noruega        Noruega     النرويج
1   86.90  ...      Denmark     Dinamarca      Dinamarca    الدنمارك
2   82.78  ...       Sweden        Suecia         Suécia      السويد
3   87.34  ...  Netherlands  Países Bajos  Países Baixos      هولندا
4   84.52  ...      Finland     Finlandia      Finlândia      فنلندا

  Country_FA Year(N) rankLastYear rankEvo scoreLastYear scoreEvo
0       نروژ    2024            1       0         95.18    -3.29
1    دانمارک    2024            3       1         89.48     0.12
2       سوئد    2024            4       1         88.15     0.17
3       هلند    2024            6       2         87.00     0.73
4     فنلاند    2024            5       0         87.94    -1.39

[5 rows x 26 columns]

In [550]:
df[['countryCode','Zone']].groupby('Zone').count()

                countryCode
Zone
Afrique                  48
Amériques                28
Asie-Pacifique           32
EEAC                     13
MENA                     19
UE Balkans               40

In [551]:
# French to English
zone_translation = {
    'Afrique': 'Africa',
    'Amériques': 'Americas',
    'Asie-Pacifique': 'Asia-Pacific',
    'EEAC': 'Eastern Europe and Central Asia',
    'MENA': 'Middle East and North Africa',
    'UE Balkans': 'EU Balkans'
}
df['Zone'] = df['Zone'].replace(zone_translation)
print(df[['countryCode', 'Zone']].groupby('Zone').count())

                                 countryCode
Zone
Africa                                    48
Americas                                  28
Asia-Pacific                              32
EU Balkans                                40
Eastern Europe and Central Asia           13
Middle East and North Africa              19

In [552]:
df[['countryCode','Situation']].groupby('Situation').count()

                         countryCode
Situation
Bonne situation                    8
Situation difficile               49
Situation plutôt bonne            37
Situation problématique           50
Situation très grave              36

In [553]:

situation_translation = {
    'Bonne situation': 'Good',
    'Situation difficile': 'Difficult',
    'Situation plutôt bonne': 'Decent',
    'Situation problématique': 'Problematic',
    'Situation très grave': 'Very serious'
}

df['Situation'] = df['Situation'].replace(situation_translation)
print(df[['countryCode', 'Situation']].groupby('Situation').count())

              countryCode
Situation
Decent                 37
Difficult              49
Good                    8
Problematic            50
Very serious           36

In [554]:
#I wonder if it makes sense to convert this into 1, 0, -1, -2, -3 instead so that it's less language specifique lol
#because I needed both chatgpt and google translate to figure out the nuances of which was worse.
#but I can do that in the end also? Shouldn't be tooooo tough to put it together and then change it 
#so I'm gonna leave it here for now.

In [555]:
print(df.columns)

Index(['countryCode', 'score', 'rank', 'polCon', 'polRank', 'ecoCon',
       'ecoRank', 'legCon', 'legRank', 'socCon', 'socRank', 'safCon',
       'safRank', 'Situation', 'Zone', 'Country_FR', 'Country_EN',
       'Country_ES', 'Country_PT', 'Country_AR', 'Country_FA', 'Year(N)',
       'rankLastYear', 'rankEvo', 'scoreLastYear', 'scoreEvo'],
      dtype='object')

In [556]:
#Okay, I think it's fairly clean and in english now.
#so since I only need the english part of all of this, I am going to create a new data frame
#and leave behind all the other countries' columns('Country_FR', 'Country_EN',
#'Country_ES', 'Country_PT', 'Country_AR', 'Country_FA'), and the Year(N) since all from 2024. 
# I feel like I don't need another column telling me the rank evolution when I have both variables to figure that out, so I'm gonna leave that out too(rankEvo)
#although now that I think about it...maybe that's more useful than rankLastYear. yeah okay. I'll keep evolution and ditch rankLastYear
# so same applies for scoreLastYear
# so the final list of everything I need:
#['countryCode', 'score', 'rank', 'polCon', 'polRank', 'ecoCon', 'ecoRank', 'legCon', 'legRank', 'socCon', 'socRank', 'safCon', 'safRank', 'Situation', 'Zone', 'Country_EN', 'rankEvo', 'scoreEvo']
# but then these names still need to change: Situation to situation, Zone to zone, Country_EN to countryName.

In [557]:
df.rename(columns={
    'Situation': 'situation',
    'Zone': 'zone',
    'Country_EN': 'countryName'
}, inplace=True)

print(df.columns)

Index(['countryCode', 'score', 'rank', 'polCon', 'polRank', 'ecoCon',
       'ecoRank', 'legCon', 'legRank', 'socCon', 'socRank', 'safCon',
       'safRank', 'situation', 'zone', 'Country_FR', 'countryName',
       'Country_ES', 'Country_PT', 'Country_AR', 'Country_FA', 'Year(N)',
       'rankLastYear', 'rankEvo', 'scoreLastYear', 'scoreEvo'],
      dtype='object')

In [558]:
RPJ_cleaned = df[['countryCode', 'score', 'rank', 'polCon', 'polRank', 'ecoCon', 'ecoRank', 'legCon', 'legRank', 'socCon', 'socRank', 'safCon', 'safRank', 'situation', 'zone', 'countryName', 'rankEvo', 'scoreEvo']].copy()
RPJ_cleaned

,countryCode,score,rank,polCon,polRank,ecoCon,ecoRank,legCon,legRank,socCon,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo
0,NOR,91.89,1,94.87,1,89.84,1,89.50,2,90.48,1,94.74,7,Good,EU Balkans,Norway,0,-3.29
1,DNK,89.60,2,94.11,2,83.07,4,88.82,3,86.90,5,95.09,5,Good,EU Balkans,Denmark,1,0.12
2,SWE,88.32,3,91.03,4,85.50,2,90.16,1,82.78,20,92.12,22,Good,EU Balkans,Sweden,1,0.17
3,NLD,87.73,4,88.41,7,84.09,3,87.59,4,87.34,4,91.23,28,Good,EU Balkans,Netherlands,2,0.73
4,FIN,86.55,5,89.05,6,80.90,5,86.16,6,84.52,14,92.13,21,Good,EU Balkans,Finland,0,-1.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,IRN,21.30,176,23.19,157,23.44,172,20.03,174,19.84,176,20.02,176,Very serious,Middle East and North Africa,Iran,1,-3.51
176,PRK,20.66,177,18.04,169,20.59,175,26.82,167,17.27,178,20.57,174,Very serious,Asia-Pacific,North Korea,3,-1.06
177,AFG,19.09,178,20.07,164,29.06,164,16.35,179,16.07,179,13.90,179,Very serious,Asia-Pacific,Afghanistan,-26,-20.66
178,SYR,17.41,179,14.35,177,19.69,177,23.75,171,17.72,177,11.55,180,Very serious,Middle East and North Africa,Syria,-4,-9.81
179,ERI,16.64,180,12.75,180,18.54,178,16.92,178,20.71,174,14.26,178,Very serious,Africa,Eritrea,-6,-11.22

In [559]:
algeria_rows = df[df['countryName'] == 'Algeria']
print(algeria_rows)

    countryCode  score  rank  polCon  polRank  ecoCon  ecoRank  legCon  \
138         DZA  41.98   139   32.16      142   32.55      153   45.43

     legRank  socCon  ...  countryName  Country_ES  Country_PT Country_AR  \
138      134   43.01  ...      Algeria     Argelia    Argélia     الجزائر

    Country_FA Year(N) rankLastYear rankEvo scoreLastYear scoreEvo
138    الجزایر    2024          136      -3         45.74    -3.76

[1 rows x 26 columns]

In [560]:
# RPJ_cleaned.to_csv('RPJ_cleaned.csv', index=True)  # Save to current working directory

In [561]:
# now for the governmental forms because I do not feel like dealing w cpj today.
cia = pd.read_csv('ciaData.csv')
print(cia.head())

          Country                                    Government Type
0     Afghanistan  theocratic; the United States does not recogni...
1         Albania                             parliamentary republic
2         Algeria                              presidential republic
3  American Samoa  unincorporated unorganized Territory of the US...
4         Andorra  parliamentary democracy (since March 1993) tha...

In [562]:
print(cia.columns)

Index(['Country', 'Government Type'], dtype='object')

In [563]:
cia.rename(columns={
    'Country': 'countryName',
    'Government Type': 'govType'
}, inplace=True)
print(cia.columns)

Index(['countryName', 'govType'], dtype='object')

In [564]:
cia[cia['countryName'].str.lower() == 'türkiye']

Empty DataFrame
Columns: [countryName, govType]
Index: []

In [565]:
'Wallis and Futuna' in df['countryName'].values

False

In [566]:
print("Countries in df:", RPJ_cleaned['countryName'].unique())
print("Countries in cia:", cia['countryName'].unique())

Countries in df: ['Norway' 'Denmark' 'Sweden' 'Netherlands' 'Finland' 'Estonia' 'Portugal'
 'Ireland' 'Switzerland' 'Germany' 'Luxembourg' 'Latvia' 'Lithuania'
 'Canada' 'Liechtenstein' 'Belgium' 'Czechia' 'Iceland' 'New Zealand'
 'East Timor' 'France' 'Samoa' 'United Kingdom' 'Jamaica'
 'Trinidad and Tobago' 'Costa Rica' 'Taiwan' 'Suriname' 'Slovakia' 'Spain'
 'Moldova' 'Austria' 'Mauritania' 'Namibia' 'Dominican Republic'
 'North Macedonia' 'Seychelles' 'South Africa' 'Australia' 'Montenegro'
 'Cabo Verde' 'Slovenia' 'Armenia' 'Fiji' 'Tonga' 'Italy' 'Poland'
 'Croatia' 'Romania' 'Ghana' 'Uruguay' 'Chile' "Côte d'Ivoire" 'Belize'
 'United States' 'Gabon' 'Mauritius' 'Gambia' 'Bulgaria' 'Liberia'
 'Ukraine' 'South Korea' 'Malawi' 'Sierra Leone' 'Cyprus' 'Argentina'
 'Hungary' 'OECS' 'Congo-Brazzaville' 'Japan' 'Comoros' 'Andorra' 'Malta'
 'Nepal' 'Kosovo' 'Central African Republic' 'Guyana' 'Guinea' 'Botswana'
 'Niger' 'Bosnia-Herzegovina' 'Brazil' 'Panama' 'Qatar' 'Eswatini'
 'Burkina Faso' 'Thailand' 'Greece' 'Benin' 'Northern Cyprus'
 'Papua New Guinea' 'Guinea-Bissau' 'Haiti' 'Senegal' 'Zambia' 'Chad'
 'Tanzania' 'Serbia' 'Albania' 'Madagascar' 'Israel' 'Kenya' 'Georgia'
 'Angola' 'Mozambique' 'Maldives' 'Malaysia' 'Burundi' 'Mongolia'
 'Ecuador' 'Indonesia' 'Nigeria' 'Togo' 'Mali' 'Paraguay' 'Zimbabwe'
 'Brunei' 'Tunisia' 'Colombia' 'Kyrgyzstan' 'Mexico' 'Lesotho' 'DR Congo'
 'Bolivia' 'Peru' 'Singapore' 'Equatorial Guinea' 'Uganda'
 'Morocco / Western Sahara ' 'Cameroon' 'Kuwait' 'Jordan' 'El Salvador'
 'Philippines' 'Hong Kong' 'South Sudan' 'Oman' 'Guatemala' 'Algeria'
 'Lebanon' 'Ethiopia' 'Kazakhstan' 'Libya' 'Rwanda' 'Somalia' 'Honduras'
 'Bhutan' 'Uzbekistan' 'Sudan' 'Sri Lanka' 'Cambodia' 'Pakistan' 'Laos'
 'Yemen' 'Tajikistan' 'Venezuela' 'Palestine' 'Türkiye' 'India'
 'United Arab Emirates' 'Djibouti' 'Russia' 'Nicaragua' 'Azerbaijan'
 'Bangladesh' 'Saudi Arabia' 'Belarus' 'Cuba' 'Iraq' 'Egypt' 'Myanmar'
 'China' 'Bahrain' 'Vietnam' 'Turkmenistan' 'Iran' 'North Korea'
 'Afghanistan' 'Syria' 'Eritrea']
Countries in cia: ['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Anguilla' 'Antarctica' 'Antigua and Barbuda' 'Argentina' 'Armenia'
 'Aruba' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma'
 'Burundi' 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Cayman Islands'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Christmas Island'
 'Cocos (Keeling) Islands' 'Colombia' 'Comoros'
 'Democratic Republic of the Congo' 'Republic of the Congo' 'Cook Islands'
 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus'
 'Czechia' 'Denmark' 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador'
 'Egypt' 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Falkland Islands (Islas Malvinas)' 'Faroe Islands' 'Fiji'
 'Finland' 'France' 'French Polynesia' 'Gabon' 'Gambia, The' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guam'
 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Holy See (Vatican City)' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland'
 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel'
 'Italy' 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kiribati' 'Korea, North' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan'
 'Laos' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Liechtenstein'
 'Lithuania' 'Luxembourg' 'Macau' 'Madagascar' 'Malawi' 'Malaysia'
 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Mauritania' 'Mauritius'
 'Mexico' 'Micronesia, Federated States of' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique' 'Namibia' 'Nauru'
 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'Niue' 'Norfolk Island' 'North Macedonia'
 'Northern Mariana Islands' 'Norway' 'Oman' 'Pakistan' 'Palau' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Pitcairn Islands'
 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint Barthelemy' 'Saint Helena, Ascension, and Tristan da Cunha'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Sint Maarten' 'Slovakia'
 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria'
 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor-Leste' 'Togo'
 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Venezuela' 'Vietnam' 'Wallis and Futuna'
 'Western Sahara' 'Yemen' 'Zambia' 'Zimbabwe']

In [567]:

sorted_RPJ_cleaned_countries = sorted(RPJ_cleaned['countryName'].unique())
sorted_cia_countries = sorted(cia['countryName'].unique())


print("Countries in RPJ_cleaned:", sorted_RPJ_cleaned_countries)
print("Countries in cia:", sorted_cia_countries)

Countries in RPJ_cleaned: ['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia-Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo-Brazzaville', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia', "Côte d'Ivoire", 'DR Congo', 'Denmark', 'Djibouti', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco / Western Sahara ', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Northern Cyprus', 'Norway', 'OECS', 'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Samoa', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkmenistan', 'Türkiye', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe']
Countries in cia: ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Falkland Islands (Islas Malvinas)', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See (Vatican City)', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea, North', 'Korea, South', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macau', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Federated States of', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Republic of the Congo', 'Romania', 'Russia', 'Rwanda', 'Saint Barthelemy', 'Saint Helena, Ascension, and Tristan da Cunha', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Wallis and Futuna', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe']

In [568]:
# Convert both columns to sets and find the intersection
common_countries = set(RPJ_cleaned['countryName']).intersection(set(cia['countryName']))
print(f"Number of countries in common: {len(common_countries)}")

Number of countries in common: 166

In [569]:
print("Common countries:", common_countries)

Common countries: {'Serbia', 'United States', 'Senegal', 'Slovakia', 'Togo', 'Switzerland', 'Jordan', 'Nigeria', 'Uganda', 'Venezuela', 'Indonesia', 'Liechtenstein', 'Malta', 'Hong Kong', 'Bangladesh', 'Panama', 'Namibia', 'Haiti', 'Samoa', 'Cyprus', 'Honduras', 'Zimbabwe', 'Comoros', 'South Africa', 'Gabon', 'United Arab Emirates', 'Mauritania', 'Jamaica', 'Kenya', 'Seychelles', 'Cabo Verde', 'Maldives', 'Somalia', 'Chad', 'Saudi Arabia', 'Fiji', 'Lithuania', 'Argentina', 'Eritrea', 'Kyrgyzstan', 'Guinea-Bissau', 'Tajikistan', 'Luxembourg', 'Australia', 'Latvia', 'Cuba', 'Estonia', 'Burkina Faso', 'Croatia', 'Thailand', 'Uruguay', 'Spain', 'Cameroon', 'Lebanon', 'Belgium', 'Ireland', 'Djibouti', 'Portugal', 'Chile', 'China', 'Albania', 'Oman', 'Suriname', 'Tunisia', 'Tanzania', 'Mongolia', 'Brunei', 'Rwanda', 'Moldova', 'Kuwait', 'Algeria', 'Guatemala', 'Israel', 'Ghana', 'Netherlands', 'Mali', 'Ecuador', 'Poland', 'North Macedonia', 'Laos', 'Afghanistan', 'Benin', 'Slovenia', 'Ukraine', 'Iraq', 'Central African Republic', 'Guyana', 'Papua New Guinea', 'Sweden', 'Angola', 'Belarus', 'Mozambique', 'Burundi', 'Eswatini', 'Vietnam', 'Germany', 'Hungary', 'Iran', 'Kazakhstan', 'Uzbekistan', 'Bolivia', 'United Kingdom', 'Egypt', 'Sudan', 'Singapore', 'El Salvador', 'Denmark', 'Czechia', 'Russia', 'Brazil', 'Canada', 'Romania', 'Peru', 'Lesotho', 'Finland', 'Nicaragua', 'Belize', 'Yemen', 'Tonga', 'Malawi', 'Pakistan', 'Greece', 'Bhutan', 'Austria', 'Ethiopia', 'Niger', 'Andorra', 'Zambia', 'Botswana', 'Georgia', 'France', 'India', 'Malaysia', 'Iceland', 'Dominican Republic', 'South Sudan', 'Nepal', 'Equatorial Guinea', 'Bahrain', 'Japan', 'Guinea', 'Montenegro', 'Liberia', 'Sierra Leone', 'Kosovo', 'New Zealand', 'Philippines', 'Costa Rica', 'Paraguay', 'Qatar', 'Norway', 'Armenia', 'Mexico', 'Libya', 'Cambodia', 'Bulgaria', 'Taiwan', 'Syria', 'Italy', 'Trinidad and Tobago', 'Madagascar', 'Mauritius', 'Azerbaijan', 'Sri Lanka', 'Colombia', 'Turkmenistan'}

In [570]:
# Convert the unique countries to sets
RPJ_cleaned_countries = set(RPJ_cleaned['countryName'].unique())
cia_countries = set(cia['countryName'].unique())

# Find countries that are only in df but not in cia
countries_in_rpj_not_in_cia = RPJ_cleaned_countries - cia_countries

# Find countries that are only in cia but not in df
countries_in_cia_not_in_rpj = cia_countries - RPJ_cleaned_countries

# Count and print the results alphabetically
print(f"Countries in df but not in cia ({len(countries_in_rpj_not_in_cia)}):", sorted(countries_in_rpj_not_in_cia))
print(f"\nCountries in cia but not in df ({len(countries_in_cia_not_in_rpj)}):", sorted(countries_in_cia_not_in_rpj))

Countries in df but not in cia (14): ['Bosnia-Herzegovina', 'Congo-Brazzaville', "Côte d'Ivoire", 'DR Congo', 'East Timor', 'Gambia', 'Morocco / Western Sahara ', 'Myanmar', 'North Korea', 'Northern Cyprus', 'OECS', 'Palestine', 'South Korea', 'Türkiye']

Countries in cia but not in df (68): ['American Samoa', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados', 'Bermuda', 'Bosnia and Herzegovina', 'British Virgin Islands', 'Burma', 'Cayman Islands', 'Christmas Island', 'Cocos (Keeling) Islands', 'Cook Islands', "Cote d'Ivoire", 'Curacao', 'Democratic Republic of the Congo', 'Dominica', 'Falkland Islands (Islas Malvinas)', 'Faroe Islands', 'French Polynesia', 'Gambia, The', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Guernsey', 'Holy See (Vatican City)', 'Isle of Man', 'Jersey', 'Kiribati', 'Korea, North', 'Korea, South', 'Macau', 'Marshall Islands', 'Micronesia, Federated States of', 'Monaco', 'Montserrat', 'Morocco', 'Nauru', 'New Caledonia', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Palau', 'Pitcairn Islands', 'Puerto Rico', 'Republic of the Congo', 'Saint Barthelemy', 'Saint Helena, Ascension, and Tristan da Cunha', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'San Marino', 'Sao Tome and Principe', 'Sint Maarten', 'Solomon Islands', 'Timor-Leste', 'Tokelau', 'Turkey', 'Turks and Caicos Islands', 'Tuvalu', 'Vanuatu', 'Wallis and Futuna', 'Western Sahara']

In [571]:
# I think it makes more sense for me to retain the countries according to df, so I should do it so that, 
#I do a join according to rpj's data and then look for the data on these ones manually and put it together. 
# Anyway that's only 11 countries, fairly doable

In [572]:
# Clean the country names in both dataframes to avoid mismatches
RPJ_cleaned['countryName'] = RPJ_cleaned['countryName'].str.strip().str.lower()
cia['countryName'] = cia['countryName'].str.strip().str.lower()

In [573]:
# So, I found a mistake in my csv where there were a ton of duplicates(my mistake in copy pasting)
#so I went through all this and then realised it makes more sense to simple go back and delete it from the csv.
#so all of this doesn't make sense anymore but I'm too lazy to delete the parts which don't make sense hence they are here.

In [574]:
# Check for duplicates in the RPJ_cleaned dataframe (before merge)
duplicates_rpj = RPJ_cleaned[RPJ_cleaned.duplicated(subset=['countryName'], keep=False)]

# Check for duplicates in the CIA dataframe (before merge)
duplicates_cia = cia[cia.duplicated(subset=['countryName'], keep=False)]

# Display duplicates (if any)
print("Duplicates in RPJ_cleaned:")
print(duplicates_rpj)
print("\nDuplicates in cia:")
print(duplicates_cia)

Duplicates in RPJ_cleaned:
Empty DataFrame
Columns: [countryCode, score, rank, polCon, polRank, ecoCon, ecoRank, legCon, legRank, socCon, socRank, safCon, safRank, situation, zone, countryName, rankEvo, scoreEvo]
Index: []

Duplicates in cia:
Empty DataFrame
Columns: [countryName, govType]
Index: []

In [575]:
# Remove duplicates across all columns
cia_cleaned = cia.drop_duplicates(keep='first')

# Check the cleaned data
print(cia_cleaned)

           countryName                                            govType
0          afghanistan  theocratic; the United States does not recogni...
1              albania                             parliamentary republic
2              algeria                              presidential republic
3       american samoa  unincorporated unorganized Territory of the US...
4              andorra  parliamentary democracy (since March 1993) tha...
..                 ...                                                ...
229  wallis and futuna  parliamentary democracy; an overseas collectiv...
230     western sahara                                 disputed territory
231              yemen                                      in transition
232             zambia                              presidential republic
233           zimbabwe                              presidential republic

[234 rows x 2 columns]

In [576]:

gov_type_mapping = {
    'bosnia-herzegovina': 'parliamentary republic',
    'congo-brazzaville': 'presidential republic',
    'côte d\'ivoire': 'Presidential republic',
    'dr congo': 'Presidential republic',
    'east timor': 'semi-presidential republic',
    'gambia': 'presidential republic',
    'morocco / western sahara ': 'Constitutional monarchy',
    'myanmar': 'Military junta',
    'north korea': 'One-party state',
    'northern cyprus': 'Presidential republic',
    'oecs': 'Parliamentary democracy',
    'palestine': 'Provisional government',
    'south korea': 'Presidential republic',
    'türkiye': 'Presidential republic'
    
}

# Create a new DataFrame from the gov_type_mapping to append to cia_cleaned
new_rows = pd.DataFrame(list(gov_type_mapping.items()), columns=['countryName', 'govType'])

# Append this new DataFrame to your existing cia_cleaned DataFrame
cia_cleaned = pd.concat([cia_cleaned, new_rows], ignore_index=True)

In [577]:
# Correct way to filter for 'northern cyprus'
cia_cleaned[cia_cleaned['countryName'] == 'northern cyprus']

         countryName                govType
243  northern cyprus  Presidential republic

In [578]:
# Perform a left join based on country names
merged_df = RPJ_cleaned.merge(cia_cleaned, on='countryName', how='left')

# Check which countries didn't have a match in cia
missing_data = merged_df[merged_df['govType'].isnull()]['countryName']
print(f"Countries with missing data ({len(missing_data)}):", missing_data.tolist())

Countries with missing data (1): ['morocco / western sahara']

In [579]:
merged_df

,countryCode,score,rank,polCon,polRank,ecoCon,ecoRank,legCon,legRank,socCon,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo,govType
0,NOR,91.89,1,94.87,1,89.84,1,89.50,2,90.48,1,94.74,7,Good,EU Balkans,norway,0,-3.29,parliamentary constitutional monarchy
1,DNK,89.60,2,94.11,2,83.07,4,88.82,3,86.90,5,95.09,5,Good,EU Balkans,denmark,1,0.12,parliamentary constitutional monarchy
2,SWE,88.32,3,91.03,4,85.50,2,90.16,1,82.78,20,92.12,22,Good,EU Balkans,sweden,1,0.17,parliamentary constitutional monarchy
3,NLD,87.73,4,88.41,7,84.09,3,87.59,4,87.34,4,91.23,28,Good,EU Balkans,netherlands,2,0.73,parliamentary constitutional monarchy; part of...
4,FIN,86.55,5,89.05,6,80.90,5,86.16,6,84.52,14,92.13,21,Good,EU Balkans,finland,0,-1.39,parliamentary republic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,IRN,21.30,176,23.19,157,23.44,172,20.03,174,19.84,176,20.02,176,Very serious,Middle East and North Africa,iran,1,-3.51,theocratic republic
176,PRK,20.66,177,18.04,169,20.59,175,26.82,167,17.27,178,20.57,174,Very serious,Asia-Pacific,north korea,3,-1.06,One-party state
177,AFG,19.09,178,20.07,164,29.06,164,16.35,179,16.07,179,13.90,179,Very serious,Asia-Pacific,afghanistan,-26,-20.66,theocratic; the United States does not recogni...
178,SYR,17.41,179,14.35,177,19.69,177,23.75,171,17.72,177,11.55,180,Very serious,Middle East and North Africa,syria,-4,-9.81,presidential republic
179,ERI,16.64,180,12.75,180,18.54,178,16.92,178,20.71,174,14.26,178,Very serious,Africa,eritrea,-6,-11.22,presidential republic

In [580]:
# Group by 'countryName' and count the occurrences of each country
country_counts = merged_df['countryName'].value_counts()

# Filter to find countries that appear more than once
duplicate_countries = country_counts[country_counts > 1]

print("Countries with duplicates:")
print(duplicate_countries)

Countries with duplicates:
Series([], Name: count, dtype: int64)

In [581]:
# Find the rows with duplicates based on 'countryName'
duplicates = cia_cleaned[cia_cleaned.duplicated(subset='countryName', keep=False)]

# Display the full rows for the duplicates
print(duplicates)

Empty DataFrame
Columns: [countryName, govType]
Index: []

In [582]:
merged_df

,countryCode,score,rank,polCon,polRank,ecoCon,ecoRank,legCon,legRank,socCon,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo,govType
0,NOR,91.89,1,94.87,1,89.84,1,89.50,2,90.48,1,94.74,7,Good,EU Balkans,norway,0,-3.29,parliamentary constitutional monarchy
1,DNK,89.60,2,94.11,2,83.07,4,88.82,3,86.90,5,95.09,5,Good,EU Balkans,denmark,1,0.12,parliamentary constitutional monarchy
2,SWE,88.32,3,91.03,4,85.50,2,90.16,1,82.78,20,92.12,22,Good,EU Balkans,sweden,1,0.17,parliamentary constitutional monarchy
3,NLD,87.73,4,88.41,7,84.09,3,87.59,4,87.34,4,91.23,28,Good,EU Balkans,netherlands,2,0.73,parliamentary constitutional monarchy; part of...
4,FIN,86.55,5,89.05,6,80.90,5,86.16,6,84.52,14,92.13,21,Good,EU Balkans,finland,0,-1.39,parliamentary republic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,IRN,21.30,176,23.19,157,23.44,172,20.03,174,19.84,176,20.02,176,Very serious,Middle East and North Africa,iran,1,-3.51,theocratic republic
176,PRK,20.66,177,18.04,169,20.59,175,26.82,167,17.27,178,20.57,174,Very serious,Asia-Pacific,north korea,3,-1.06,One-party state
177,AFG,19.09,178,20.07,164,29.06,164,16.35,179,16.07,179,13.90,179,Very serious,Asia-Pacific,afghanistan,-26,-20.66,theocratic; the United States does not recogni...
178,SYR,17.41,179,14.35,177,19.69,177,23.75,171,17.72,177,11.55,180,Very serious,Middle East and North Africa,syria,-4,-9.81,presidential republic
179,ERI,16.64,180,12.75,180,18.54,178,16.92,178,20.71,174,14.26,178,Very serious,Africa,eritrea,-6,-11.22,presidential republic

In [583]:
# Filter rows where govType is NaN
govtype_na_rows = merged_df[merged_df['govType'].isna()]

# Print these rows
print(govtype_na_rows)

    countryCode  score  rank  polCon  polRank  ecoCon  ecoRank  legCon  \
128         MAR  45.97   129   40.31      119   35.68      135   48.92

     legRank  socCon  socRank  safCon  safRank  situation  \
128      128    50.3      125   54.63      123  Difficult

                             zone               countryName  rankEvo  \
128  Middle East and North Africa  morocco / western sahara       15

     scoreEvo govType
128      2.28     NaN

In [584]:
print(f"Number of rows with NaN in govType: {govtype_na_rows.shape[0]}")

Number of rows with NaN in govType: 1

In [585]:
merged_df.to_csv('RPJ_CIA.csv', index=True)

In [586]:
# Okay, cpj still hasnt responded so I'm gonna do unesco now, and the cpj data I have.
# And then after that we'll see about the data I don't have.

In [587]:
unesco = pd.read_csv("unesco_killedData.csv", encoding='UTF-8')

In [588]:
unesco

,Name,Gender,Date killed,Nationality,Judicial enquiry status,Country where killed
0,Abdallah Al Karkaai (aka Abdelsalam Al Kahla),Male,"April 27, 2015",Libyan,No Information Received So Far,Libya
1,Abdallah Bouhecheck,Male,"February 10, 1996",Algerian,NaN,Algeria
2,Abdel Hakim Al-Nour,Male,"October 4, 2011",Yemeni,No Information Received So Far,Yemen
3,Abdel Hussein Khazaal,Male,"February 9, 2005",Iraqi,NaN,Iraq
4,Abdel Karim al-Rubai,Male,"September 9, 2006",Iraqi,Ongoing/Unresolved,Iraq
...,...,...,...,...,...,...
1716,Ziad Al-Sharabi,Male,"January 28, 2019",Yemeni,No Information Received So Far,Yemen
1717,Zine Eddine Aliou Salah,Male,"January 6, 1995",Algerian,NaN,Algeria
1718,Zoreslav Zamoysky,Male,"March 5, 2022",Ukrainian,Ongoing/Unresolved,Ukraine
1719,Zubair Ahmed Mujahid,Male,"November 23, 2007",Pakistani,Ongoing/Unresolved,Pakistan
1720,Zulfiqar Ali Mandrani,Male,"May 26, 2020",Pakistani,No Information Received So Far,Pakistan

In [589]:
len(unesco['Country where killed'].unique())

103

In [590]:
# Okay. a couple of things though. I have the country these journalists were killed in, and the country these journalists are from. 
# If I'm merging it with my rpj and governmental form data, do you think I should merge based on the nationality or the country where killed?
# I feel the nationality makes it about identity, but country where killed is more in line with the idea of a human first approach to my dataset?
# but wouldn't it be suuuper interesting to see if certain natioanlities people get targetted?
#but my original thought here was about a human first approach, so that raises a different idea anyway. 
#I think country where killed is the correct form for that idea.

In [591]:
#BUT.
#still, if it's a human first approach, does that mean, that the name of the person should come first, and then the name of the country?
#but then we have a lot more countries than those that people are killed in. I think, I can revisit this before I decide on nesting anything.
#for now let's clean unesco and put it together and see what it looks like.

In [592]:
#WAIT NO THAT'S it.
#as long as I don't nest several journalists into one cell, it's still human first, in my opinion. 
#So no nesting there. As long as no nesting, concept still stands.

In [593]:
unesco.rename(columns={
    'Name': 'fullName',
    'Date killed': 'dateKilled',
    'Judicial enquiry status': 'judicialEnquiryStatus',
    'Gender': 'gender',
    'Nationality': 'nationality',
    'Country where killed': 'countryWhereHarmed'
    
}, inplace=True)
print(unesco.columns)

Index(['fullName', 'gender', 'dateKilled', 'nationality',
       'judicialEnquiryStatus', 'countryWhereHarmed'],
      dtype='object')

In [594]:
unesco

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed
0,Abdallah Al Karkaai (aka Abdelsalam Al Kahla),Male,"April 27, 2015",Libyan,No Information Received So Far,Libya
1,Abdallah Bouhecheck,Male,"February 10, 1996",Algerian,NaN,Algeria
2,Abdel Hakim Al-Nour,Male,"October 4, 2011",Yemeni,No Information Received So Far,Yemen
3,Abdel Hussein Khazaal,Male,"February 9, 2005",Iraqi,NaN,Iraq
4,Abdel Karim al-Rubai,Male,"September 9, 2006",Iraqi,Ongoing/Unresolved,Iraq
...,...,...,...,...,...,...
1716,Ziad Al-Sharabi,Male,"January 28, 2019",Yemeni,No Information Received So Far,Yemen
1717,Zine Eddine Aliou Salah,Male,"January 6, 1995",Algerian,NaN,Algeria
1718,Zoreslav Zamoysky,Male,"March 5, 2022",Ukrainian,Ongoing/Unresolved,Ukraine
1719,Zubair Ahmed Mujahid,Male,"November 23, 2007",Pakistani,Ongoing/Unresolved,Pakistan
1720,Zulfiqar Ali Mandrani,Male,"May 26, 2020",Pakistani,No Information Received So Far,Pakistan

In [595]:
#but there is a problem.
#this is just the killed list. Now there will be the imprisoned and missing ones too.
#So I need an additional column that explains what the issue is.

In [596]:
unesco['status'] = 'killed'
print(unesco.head())

                                        fullName gender         dateKilled  \
0  Abdallah Al Karkaai (aka Abdelsalam Al Kahla)   Male     April 27, 2015
1                            Abdallah Bouhecheck   Male  February 10, 1996
2                            Abdel Hakim Al-Nour   Male    October 4, 2011
3                          Abdel Hussein Khazaal   Male   February 9, 2005
4                           Abdel Karim al-Rubai   Male  September 9, 2006

  nationality           judicialEnquiryStatus countryWhereHarmed  status
0      Libyan  No Information Received So Far              Libya  killed
1    Algerian                             NaN            Algeria  killed
2      Yemeni  No Information Received So Far              Yemen  killed
3       Iraqi                             NaN               Iraq  killed
4       Iraqi              Ongoing/Unresolved               Iraq  killed

In [597]:
unesco['dateKilled'] = pd.to_datetime(unesco['dateKilled'], format='%B %d, %Y')
unesco

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed,status
0,Abdallah Al Karkaai (aka Abdelsalam Al Kahla),Male,2015-04-27,Libyan,No Information Received So Far,Libya,killed
1,Abdallah Bouhecheck,Male,1996-02-10,Algerian,NaN,Algeria,killed
2,Abdel Hakim Al-Nour,Male,2011-10-04,Yemeni,No Information Received So Far,Yemen,killed
3,Abdel Hussein Khazaal,Male,2005-02-09,Iraqi,NaN,Iraq,killed
4,Abdel Karim al-Rubai,Male,2006-09-09,Iraqi,Ongoing/Unresolved,Iraq,killed
...,...,...,...,...,...,...,...
1716,Ziad Al-Sharabi,Male,2019-01-28,Yemeni,No Information Received So Far,Yemen,killed
1717,Zine Eddine Aliou Salah,Male,1995-01-06,Algerian,NaN,Algeria,killed
1718,Zoreslav Zamoysky,Male,2022-03-05,Ukrainian,Ongoing/Unresolved,Ukraine,killed
1719,Zubair Ahmed Mujahid,Male,2007-11-23,Pakistani,Ongoing/Unresolved,Pakistan,killed
1720,Zulfiqar Ali Mandrani,Male,2020-05-26,Pakistani,No Information Received So Far,Pakistan,killed

In [598]:
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].str.strip().str.lower()
unesco

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed,status
0,Abdallah Al Karkaai (aka Abdelsalam Al Kahla),Male,2015-04-27,Libyan,No Information Received So Far,libya,killed
1,Abdallah Bouhecheck,Male,1996-02-10,Algerian,NaN,algeria,killed
2,Abdel Hakim Al-Nour,Male,2011-10-04,Yemeni,No Information Received So Far,yemen,killed
3,Abdel Hussein Khazaal,Male,2005-02-09,Iraqi,NaN,iraq,killed
4,Abdel Karim al-Rubai,Male,2006-09-09,Iraqi,Ongoing/Unresolved,iraq,killed
...,...,...,...,...,...,...,...
1716,Ziad Al-Sharabi,Male,2019-01-28,Yemeni,No Information Received So Far,yemen,killed
1717,Zine Eddine Aliou Salah,Male,1995-01-06,Algerian,NaN,algeria,killed
1718,Zoreslav Zamoysky,Male,2022-03-05,Ukrainian,Ongoing/Unresolved,ukraine,killed
1719,Zubair Ahmed Mujahid,Male,2007-11-23,Pakistani,Ongoing/Unresolved,pakistan,killed
1720,Zulfiqar Ali Mandrani,Male,2020-05-26,Pakistani,No Information Received So Far,pakistan,killed

In [599]:
print(unesco[unesco['countryWhereHarmed'].isna()])

            fullName gender dateKilled nationality judicialEnquiryStatus  \
530   Gabriel Grüner   Male 1999-06-13     Italian                   NaN
1527   Shefki Popova   Male 2000-09-10         NaN                   NaN
1641   Volker Krämer   Male 1999-06-13      German                   NaN

     countryWhereHarmed  status
530                 NaN  killed
1527                NaN  killed
1641                NaN  killed

In [600]:
#looking into missing countries
missing_nationality_rows = unesco[pd.isna(unesco['nationality'])]
print(missing_nationality_rows)

           fullName gender dateKilled nationality judicialEnquiryStatus  \
1527  Shefki Popova   Male 2000-09-10         NaN                   NaN

     countryWhereHarmed  status
1527                NaN  killed

In [601]:
# Replace NaN values for the specific row
unesco.loc[1527] = unesco.loc[1527].fillna({
    'nationality': 'Kosovar/Albanian',
    'judicialEnquiryStatus': 'unresolved',
    'countryWhereHarmed': 'albania'
})
unesco.loc[530] = unesco.loc[530].fillna({
    
    'judicialEnquiryStatus': 'unresolved',
    'countryWhereHarmed': 'kosovo'
})
unesco.loc[1641] = unesco.loc[1641].fillna({
    
    'judicialEnquiryStatus': 'unresolved',
    'countryWhereHarmed': 'kosovo'
})

# Verify the changes
print(unesco.loc[1527])
print(unesco.loc[530])
print(unesco.loc[1641])

fullName                       Shefki Popova
gender                                  Male
dateKilled               2000-09-10 00:00:00
nationality                 Kosovar/Albanian
judicialEnquiryStatus             unresolved
countryWhereHarmed                   albania
status                                killed
Name: 1527, dtype: object
fullName                      Gabriel Grüner
gender                                  Male
dateKilled               1999-06-13 00:00:00
nationality                          Italian
judicialEnquiryStatus             unresolved
countryWhereHarmed                    kosovo
status                                killed
Name: 530, dtype: object
fullName                       Volker Krämer
gender                                  Male
dateKilled               1999-06-13 00:00:00
nationality                           German
judicialEnquiryStatus             unresolved
countryWhereHarmed                    kosovo
status                                killed
Name: 1641, dtype: object

In [602]:
#need to fix 'viet nam' in countryWhereHarmed
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('viet nam', 'vietnam')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('venezuela (bolivarian republic of)', 'venezuela')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('state of palestine', 'palestine')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('syrian arab republic', 'syria')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('united republic of tanzania', 'tanzania')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('bolivia (plurinational state of)', 'bolivia')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('iran (islamic republic of)', 'iran')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('russian federation', 'russia')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('united kingdom of great britain and northern ireland', 'united kingdom')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('democratic republic of the congo', 'dr congo')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('republic of the congo', 'congo-brazzaville')
unesco['countryWhereHarmed'] = unesco['countryWhereHarmed'].replace('congo', 'congo-brazzaville')

In [603]:
merged_df['countryName'] = merged_df['countryName'].replace('united states', 'united states of america')

In [604]:
cia_rpj_unesco = unesco.merge(merged_df, how='outer', left_on='countryWhereHarmed', right_on='countryName')
cia_rpj_unesco

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed,status,countryCode,score,rank,...,socCon,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo,govType
0,Abdul Manan Arghand,Male,2018-04-25,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
1,Abdul Qodus,Male,2006-07-22,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
2,Abdul Samad Rohani,Male,2008-06-07,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
3,Ahmad Khan Nawid,Male,2020-05-09,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
4,Ahmad Shah,Male,2018-04-30,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,Wael Al-Absi,Male,2017-05-26,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1795,Youssef Alaizry,Male,2015-05-20,Yemeni,Ongoing/Unresolved,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1796,Ziad Al-Sharabi,Male,2019-01-28,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1797,NaN,NaN,NaT,NaN,NaN,NaN,NaN,ZMB,55.38,95.0,...,55.95,110.0,83.93,66.0,Problematic,Africa,zambia,-8.0,-4.03,presidential republic
1798,NaN,NaN,NaT,NaN,NaN,NaN,NaN,ZWE,50.31,116.0,...,52.68,118.0,68.50,101.0,Difficult,Africa,zimbabwe,10.0,2.14,presidential republic

In [605]:
cia_rpj_unesco['role'] = 'journalist'
cia_rpj_unesco

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed,status,countryCode,score,rank,...,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo,govType,role
0,Abdul Manan Arghand,Male,2018-04-25,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
1,Abdul Qodus,Male,2006-07-22,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
2,Abdul Samad Rohani,Male,2008-06-07,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
3,Ahmad Khan Nawid,Male,2020-05-09,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
4,Ahmad Shah,Male,2018-04-30,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,Wael Al-Absi,Male,2017-05-26,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition,journalist
1795,Youssef Alaizry,Male,2015-05-20,Yemeni,Ongoing/Unresolved,yemen,killed,YEM,33.67,154.0,...,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition,journalist
1796,Ziad Al-Sharabi,Male,2019-01-28,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition,journalist
1797,NaN,NaN,NaT,NaN,NaN,NaN,NaN,ZMB,55.38,95.0,...,110.0,83.93,66.0,Problematic,Africa,zambia,-8.0,-4.03,presidential republic,journalist
1798,NaN,NaN,NaT,NaN,NaN,NaN,NaN,ZWE,50.31,116.0,...,118.0,68.50,101.0,Difficult,Africa,zimbabwe,10.0,2.14,presidential republic,journalist

In [606]:
#this is so cool. The countries which have terrible indices but 'NaN' for journalists means the condition is so bad
#that if people are dying, the data isn't makign it out. If they aren't a possible reason is that people are too scared?
# i mean ofc it's not cool it's terrible.
# Okay I kinda feel like taking care of the nans before moving on because there are quite a few of them now.

In [607]:
#After further thought, I'm removing the countries that do not have fullName
cia_rpj_unesco = cia_rpj_unesco.dropna(subset=['fullName'])

In [608]:
#need to check how many countries have Nan--this will be new now because of the merge

In [609]:
# Filter rows where 'countryCode' is NaN
toFix = cia_rpj_unesco[cia_rpj_unesco['countryCode'].isna()]

# Group by 'countryWhereHarmed'
toFix_cwh = toFix.groupby('countryWhereHarmed')

# Example: Count occurrences in each group
toFix_cwh_counts = toFix_cwh.size()

# Print the counts of each group
print(toFix_cwh_counts)

countryWhereHarmed
barbados    1
dtype: int64

In [610]:
for group_name, group_data in toFix_cwh:
    print(f"Group: {group_name}")
    print(group_data)

Group: barbados
               fullName gender dateKilled nationality  \
174  Christoff Griffith   Male 2020-06-22   Barbadian

              judicialEnquiryStatus countryWhereHarmed  status countryCode  \
174  No Information Received So Far           barbados  killed         NaN

     score  rank  ...  socRank  safCon  safRank  situation  zone  countryName  \
174    NaN   NaN  ...      NaN     NaN      NaN        NaN   NaN          NaN

     rankEvo  scoreEvo  govType        role
174      NaN       NaN      NaN  journalist

[1 rows x 27 columns]

In [611]:
cia_rpj_unesco[cia_rpj_unesco['countryWhereHarmed'] != cia_rpj_unesco['countryName']]

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed,status,countryCode,score,rank,...,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo,govType,role
174,Christoff Griffith,Male,2020-06-22,Barbadian,No Information Received So Far,barbados,killed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,journalist

In [612]:
cia_rpj_unesco

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed,status,countryCode,score,rank,...,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo,govType,role
0,Abdul Manan Arghand,Male,2018-04-25,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
1,Abdul Qodus,Male,2006-07-22,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
2,Abdul Samad Rohani,Male,2008-06-07,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
3,Ahmad Khan Nawid,Male,2020-05-09,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
4,Ahmad Shah,Male,2018-04-30,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...,journalist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,Suad Hujaira,Female,2016-02-09,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition,journalist
1793,Taqi Al-Din Al-Huthaifi,Male,2017-05-26,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition,journalist
1794,Wael Al-Absi,Male,2017-05-26,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition,journalist
1795,Youssef Alaizry,Male,2015-05-20,Yemeni,Ongoing/Unresolved,yemen,killed,YEM,33.67,154.0,...,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition,journalist
1796,Ziad Al-Sharabi,Male,2019-01-28,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition,journalist

In [613]:
merged_df[['countryName', 'countryCode', 'score', 'polCon']]

     countryName countryCode  score  polCon
0         norway         NOR  91.89   94.87
1        denmark         DNK  89.60   94.11
2         sweden         SWE  88.32   91.03
3    netherlands         NLD  87.73   88.41
4        finland         FIN  86.55   89.05
..           ...         ...    ...     ...
175         iran         IRN  21.30   23.19
176  north korea         PRK  20.66   18.04
177  afghanistan         AFG  19.09   20.07
178        syria         SYR  17.41   14.35
179      eritrea         ERI  16.64   12.75

[180 rows x 4 columns]

In [614]:
#okay let's look into cpj missing. can look into killing and imprisoned there later I suppose.

In [615]:
cpj_missing = pd.read_csv("cpj_missingData.csv", encoding='UTF-8')

In [616]:
cpj_missing.columns

Index(['year', 'combinedStatus', 'fullName', 'sortName', 'primaryNationality',
       'secondaryNationality', 'tertiaryNationality', 'gender', 'photoUrl',
       'photoCredit', 'type', 'lastStatus', 'typeOfDeath', 'status',
       'employedAs', 'organizations', 'jobs', 'coverage', 'mediums', 'country',
       'location', 'region', 'state', 'locality', 'province', 'localOrForeign',
       'sourcesOfFire', 'motiveConfirmed', 'accountabilityCrossfire',
       'accountabilityAssignment', 'impunityMurder', 'tortured', 'captive',
       'threatened', 'charges', 'motive', 'lengthOfSentence', 'healthProblems',
       'impCountry', 'entry', 'sentenceDate', 'sentence',
       'locationImprisoned'],
      dtype='object')

In [617]:
#sortName is useless, all nationalities can be put into one column and separated by /,
# since this is both media workers and journalists I need to change the columns of 'journalist' into the personName. And add a column that says 'role.'

In [618]:

cia_rpj_unesco = unesco.merge(merged_df, how='outer', left_on='countryWhereHarmed', right_on='countryName')
cia_rpj_unesco

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed,status,countryCode,score,rank,...,socCon,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo,govType
0,Abdul Manan Arghand,Male,2018-04-25,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
1,Abdul Qodus,Male,2006-07-22,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
2,Abdul Samad Rohani,Male,2008-06-07,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
3,Ahmad Khan Nawid,Male,2020-05-09,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
4,Ahmad Shah,Male,2018-04-30,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,Wael Al-Absi,Male,2017-05-26,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1795,Youssef Alaizry,Male,2015-05-20,Yemeni,Ongoing/Unresolved,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1796,Ziad Al-Sharabi,Male,2019-01-28,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1797,NaN,NaN,NaT,NaN,NaN,NaN,NaN,ZMB,55.38,95.0,...,55.95,110.0,83.93,66.0,Problematic,Africa,zambia,-8.0,-4.03,presidential republic
1798,NaN,NaN,NaT,NaN,NaN,NaN,NaN,ZWE,50.31,116.0,...,52.68,118.0,68.50,101.0,Difficult,Africa,zimbabwe,10.0,2.14,presidential republic

In [619]:
cia_rpj_unesco = cia_rpj_unesco[cia_rpj_unesco['fullName'].notna()].copy()
cia_rpj_unesco

,fullName,gender,dateKilled,nationality,judicialEnquiryStatus,countryWhereHarmed,status,countryCode,score,rank,...,socCon,socRank,safCon,safRank,situation,zone,countryName,rankEvo,scoreEvo,govType
0,Abdul Manan Arghand,Male,2018-04-25,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
1,Abdul Qodus,Male,2006-07-22,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
2,Abdul Samad Rohani,Male,2008-06-07,Afghan,Resolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
3,Ahmad Khan Nawid,Male,2020-05-09,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
4,Ahmad Shah,Male,2018-04-30,Afghan,Ongoing/Unresolved,afghanistan,killed,AFG,19.09,178.0,...,16.07,179.0,13.90,179.0,Very serious,Asia-Pacific,afghanistan,-26.0,-20.66,theocratic; the United States does not recogni...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,Suad Hujaira,Female,2016-02-09,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1793,Taqi Al-Din Al-Huthaifi,Male,2017-05-26,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1794,Wael Al-Absi,Male,2017-05-26,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1795,Youssef Alaizry,Male,2015-05-20,Yemeni,Ongoing/Unresolved,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition
1796,Ziad Al-Sharabi,Male,2019-01-28,Yemeni,No Information Received So Far,yemen,killed,YEM,33.67,154.0,...,31.43,159.0,34.67,154.0,Very serious,Middle East and North Africa,yemen,14.0,0.89,in transition

In [620]:
# Find all NaN values in the DataFrame
nan_locations = cia_rpj_unesco.isna()

# Check which columns have NaN values
nan_summary = nan_locations.sum()
print(nan_summary)

fullName                   0
gender                     0
dateKilled                 0
nationality                0
judicialEnquiryStatus    206
countryWhereHarmed         0
status                     0
countryCode                1
score                      1
rank                       1
polCon                     1
polRank                    1
ecoCon                     1
ecoRank                    1
legCon                     1
legRank                    1
socCon                     1
socRank                    1
safCon                     1
safRank                    1
situation                  1
zone                       1
countryName                1
rankEvo                    1
scoreEvo                   1
govType                    1
dtype: int64

In [621]:
#after this I started using data that I don't think I can finish looking into so I'm gonna leave it here for now.

In [622]:
#now That I've had a couple days to think about it, I think dropping the countries which don't have any journalists doesn't make sense, 
#simply because that is very different information from something like 'unknown'. So let's simple look at that for now.

In [623]:

# Algeria, Burundi, China
#14 countries govType

In [624]:
#fix goverments, and drop that one row with christoff griffith.
# Drop a column by specifying its name
cia_rpj_unesco = cia_rpj_unesco.drop('judicialEnquiryStatus', axis=1)

In [625]:
#i dont have rpj data for barbados so poor christoff I need to remove
cia_rpj_unesco = cia_rpj_unesco.drop(174, axis=0);
cia_rpj_unesco = cia_rpj_unesco.reset_index(drop=True);

In [626]:
# Find all NaN values in the DataFrame
nan_locations = cia_rpj_unesco.isna()

# Check which columns have NaN values
nan_summary = nan_locations.sum()
print(nan_summary)

fullName              0
gender                0
dateKilled            0
nationality           0
countryWhereHarmed    0
status                0
countryCode           0
score                 0
rank                  0
polCon                0
polRank               0
ecoCon                0
ecoRank               0
legCon                0
legRank               0
socCon                0
socRank               0
safCon                0
safRank               0
situation             0
zone                  0
countryName           0
rankEvo               0
scoreEvo              0
govType               0
dtype: int64

In [627]:
# Find all NaN values in the DataFrame
nan_locations = cia_rpj_unesco['govType'].isna()

# Check which columns have NaN values
nan_summary = nan_locations.sum()
print(cia_rpj_unesco[nan_locations])

Empty DataFrame
Columns: [fullName, gender, dateKilled, nationality, countryWhereHarmed, status, countryCode, score, rank, polCon, polRank, ecoCon, ecoRank, legCon, legRank, socCon, socRank, safCon, safRank, situation, zone, countryName, rankEvo, scoreEvo, govType]
Index: []

[0 rows x 25 columns]

In [628]:
# Export the DataFrame to a CSV file
cia_rpj_unesco.to_csv('cia_rpj_unesco.csv', index=False)